apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locationApi
  name: udaconnect-locationApi
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: udaconnect-locationApi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locationApi
  name: udaconnect-locationApi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locationApi
  template:
    metadata:
      labels:
        service: udaconnect-locationApi
    spec:
      containers:
      - image: nickwooduk/nd064-udaconnect-locationApi:master
        name: udaconnect-locationApi
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
